import {
	applyDecorators,
	Delete,
	Get,
	HttpCode,
	Patch,
	Post,
	Put,
	Version,
} from '@nestjs/common'
import {
	ApiBody,
	ApiHeader,
	ApiOperation,
	ApiParam,
	ApiQuery,
	ApiResponse,
} from '@nestjs/swagger'
import type { SchemaObject } from '@nestjs/swagger/dist/interfaces/open-api-spec.interface.js'
import type { z } from 'zod'

import { EXCEPTION_SCHEMA_REF } from '@/openapi/openapi.errors.js'
import { toJsonSchema } from '@/openapi/openapi.utils.js'

/** Zod schemas for request validation (params, query, body, headers). */
export type RouteParameters = {
	/** Header validation schema. */
	headers?: z.ZodObject<z.ZodRawShape>
	/** URL path-parameter validation schema. */
	params?: z.ZodObject<z.ZodRawShape>
	/** Query-string validation schema. Supports intersections for composed schemas. */
	query?:
		| z.ZodObject<z.ZodRawShape>
		| z.ZodIntersection<z.ZodSchema, z.ZodSchema>
	/** Request body validation schema. */
	body?: z.ZodSchema
}

/**
 * An exception class generated by `createExceptions` from
 * `@turystack/exceptions` (duck-typed, so any copy of the package matches):
 * carries a static literal `code` and instances expose the HTTP `statusCode`.
 */
export type RouteExceptionClass = (new (
	...args: never[]
) => {
	statusCode: number
	code: string
	message: string
}) & {
	readonly code: string
}

/** Response schemas keyed by HTTP status code. */
export type RouteResponses = {
	/** Success response schema. */
	200?: z.ZodSchema
	/** Created response schema. */
	201?: z.ZodSchema
	/** No Content response description. */
	204?: {
		description: string
	}
	/**
	 * Exception classes this route can return — status, code, and OpenAPI
	 * examples are derived from the classes themselves; the server only
	 * displays what the catalog already declares.
	 */
	exceptions?: RouteExceptionClass[]
}

/**
 * Options for the {@link Route} decorator.
 *
 * @example
 * ```ts
 * @Route({
 *   method: 'GET',
 *   path: ':id',
 *   summary: 'Get User',
 *   description: 'Returns a single user by ID',
 *   parameters: { params: schema.params },
 *   responses: { 200: UserResponseSchema },
 * })
 * ```
 */
type RouteOptions = {
	/** API version number. Defaults to `1`. */
	version?: number
	/** Route path (appended to the controller prefix). */
	path?: string
	/** HTTP method. */
	method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE'
	/** Swagger operation summary. */
	summary: string
	/** Swagger operation description. */
	description: string
	/** Request validation schemas. */
	parameters?: RouteParameters
	/** Response schemas by status code. */
	responses?: RouteResponses
}

const HTTP_METHOD_DECORATORS = {
	DELETE: Delete,
	GET: Get,
	PATCH: Patch,
	POST: Post,
	PUT: Put,
} as const

/**
 * Resolves the turystack custom-method syntax: `::verb` marks a business
 * action on the resource (`':invoiceId::pay'` → matches `/invoices/123:pay`).
 * The literal colon is escaped for the Express 5 path matcher, and a custom
 * method is only valid on POST — anything else fails at boot.
 */
function resolvePath(
	path: string | undefined,
	method: keyof typeof HTTP_METHOD_DECORATORS,
): string | undefined {
	if (!path?.includes('::')) {
		return path
	}

	if (method !== 'POST') {
		throw new Error(`[Route] custom method path '${path}' requires method POST`)
	}

	return path.replaceAll('::', '\\:')
}

function createParamDecorators(
	params: z.ZodObject<z.ZodRawShape>,
): MethodDecorator[] {
	const shape = params.shape

	return Object.entries(shape).map(([name, schema]) => {
		const jsonSchema = toJsonSchema(schema as z.ZodSchema, 'input')
		return ApiParam({
			name,
			schema: jsonSchema,
		})
	})
}

function extractPropertiesFromSchema(schema: SchemaObject): {
	properties: Record<string, SchemaObject>
	required: string[]
} {
	let properties: Record<string, SchemaObject> = {}
	let required: string[] = []

	if (schema.properties) {
		properties = {
			...properties,
			...(schema.properties as Record<string, SchemaObject>),
		}
	}

	if (schema.required) {
		required = [
			...required,
			...(schema.required as string[]),
		]
	}

	if (schema.allOf) {
		for (const item of schema.allOf) {
			const nested = extractPropertiesFromSchema(item as SchemaObject)
			properties = {
				...properties,
				...nested.properties,
			}
			required = [
				...required,
				...nested.required,
			]
		}
	}

	return {
		properties,
		required,
	}
}

function createQueryDecorators(
	query:
		| z.ZodObject<z.ZodRawShape>
		| z.ZodIntersection<z.ZodSchema, z.ZodSchema>,
): MethodDecorator[] {
	const jsonSchema = toJsonSchema(query, 'input')
	const { properties, required } = extractPropertiesFromSchema(jsonSchema)

	return Object.entries(properties).map(([name, propSchema]) => {
		const hasDefault = 'default' in propSchema
		const isRequired = !hasDefault && required.includes(name)

		return ApiQuery({
			name,
			required: isRequired,
			schema: propSchema,
		})
	})
}

function createHeaderDecorators(
	headers: z.ZodObject<z.ZodRawShape>,
): MethodDecorator[] {
	const shape = headers.shape

	return Object.entries(shape).map(([name, schema]) => {
		const jsonSchema = toJsonSchema(schema as z.ZodSchema, 'input')
		const isRequired = !(schema as z.ZodSchema).isOptional()

		return ApiHeader({
			description: jsonSchema.description,
			name,
			required: isRequired,
			schema: jsonSchema,
		})
	})
}

function createBodyDecorator(body: z.ZodSchema): MethodDecorator {
	return ApiBody({
		schema: toJsonSchema(body, 'input'),
	})
}

function createResponseDecorators(
	responses: RouteResponses,
): MethodDecorator[] {
	const decorators: MethodDecorator[] = []

	if (responses[200]) {
		decorators.push(
			ApiResponse({
				content: {
					'application/json': {
						schema: toJsonSchema(responses[200]),
					},
				},
				description: 'OK',
				status: 200,
			}),
		)
	}

	if (responses[201]) {
		decorators.push(
			ApiResponse({
				content: {
					'application/json': {
						schema: toJsonSchema(responses[201]),
					},
				},
				description: 'Created',
				status: 201,
			}),
		)
	}

	if (responses[204]) {
		decorators.push(
			ApiResponse({
				content: {
					'application/json': {
						examples: {
							[`204-${responses[204].description}`]: {
								summary: responses[204].description,
							},
						},
					},
				},
				description: responses[204].description,
				status: 204,
			}),
		)
	}

	if (responses.exceptions?.length) {
		decorators.push(...createExceptionResponseDecorators(responses.exceptions))
	}

	return decorators
}

function createExceptionResponseDecorators(
	exceptions: RouteExceptionClass[],
): MethodDecorator[] {
	const byStatus = new Map<number, RouteExceptionClass[]>()

	for (const ExceptionClass of exceptions) {
		const status = new ExceptionClass().statusCode
		byStatus.set(status, [
			...(byStatus.get(status) ?? []),
			ExceptionClass,
		])
	}

	return [
		...byStatus.entries(),
	].map(([status, classes]) => {
		const examples = classes.reduce(
			(acc, ExceptionClass, index) => {
				acc[`${status}-${ExceptionClass.code}-${index + 1}`] = {
					summary: ExceptionClass.code,
					value: {
						code: ExceptionClass.code,
						message: ExceptionClass.code,
						statusCode: status,
						...(status === 404
							? {
									resourceId: '<resource-id>',
								}
							: {}),
					},
				}
				return acc
			},
			{} as Record<
				string,
				{
					summary: string
					value: object
				}
			>,
		)

		return ApiResponse({
			content: {
				'application/json': {
					examples,
					schema: EXCEPTION_SCHEMA_REF,
				},
			},
			description: ERROR_DESCRIPTIONS[status] ?? 'Error',
			status,
		})
	})
}

const ERROR_DESCRIPTIONS: Record<number, string> = {
	400: 'Bad Request Error',
	401: 'Unauthorized Error',
	403: 'Forbidden Error',
	404: 'Not Found Error',
	409: 'Conflict Error',
	410: 'Gone Error',
	422: 'Unprocessable Entity Error',
	429: 'Too Many Requests Error',
	500: 'Internal Server Error',
}

function createDefaultQueryDecorators(): MethodDecorator[] {
	return [
		ApiQuery({
			description:
				'Comma-separated list of fields to include in the response. Supports dot notation for nested projection (e.g. `id,name,user.email,trips.route.id`). Unknown fields are silently dropped.',
			example: 'id,name',
			name: 'fields',
			required: false,
			schema: {
				type: 'string',
			},
		}),
	]
}

function createDefaultErrorResponses() {
	const decorators: MethodDecorator[] = []

	decorators.push(
		ApiResponse({
			content: {
				'application/json': {
					example: {
						code: 'validation.invalid_payload',
						errors: [
							{
								code: 'invalid_type',
								message: 'Obrigatório',
								path: 'name',
							},
						],
						message: 'Dados inválidos',
						statusCode: 400,
					},
					schema: EXCEPTION_SCHEMA_REF,
				},
			},
			description: 'Bad Request Error',
			status: 400,
		}),
	)

	decorators.push(
		ApiResponse({
			content: {
				'application/json': {
					example: {
						message: 'Internal Server Error',
						statusCode: 500,
					},
					schema: EXCEPTION_SCHEMA_REF,
				},
			},
			description: 'Internal Server Error',
			status: 500,
		}),
	)

	return decorators
}

function getHttpStatusCode(responses?: RouteResponses): number {
	if (!responses) {
		return 204
	}

	const successCodes = [
		200,
		201,
		204,
	]
	for (const code of successCodes) {
		if (code in responses) {
			return code
		}
	}

	return 204
}

/**
 * Method decorator combining HTTP method, Swagger docs, and Zod validation in one.
 *
 * Automatically generates inline Swagger `@ApiParam`, `@ApiQuery`, `@ApiBody`,
 * `@ApiResponse` decorators from the provided Zod schemas.
 * Also registers default 400 and 500 error responses.
 *
 * @example
 * ```ts
 * import { Route } from '@/infrastructure/server/decorators/route.decorator'
 *
 * @Route({
 *   method: 'POST',
 *   path: ':id::activate',
 *   summary: 'Activate User',
 *   description: 'Activates a user by ID',
 *   parameters: { params: z.object({ id: z.string().uuid() }) },
 *   responses: { 200: UserResponseSchema },
 * })
 * async activateUser() {}
 * ```
 */
export function Route(options: RouteOptions): MethodDecorator {
	return (
		target: object,
		propertyKey: string | symbol,
		descriptor: PropertyDescriptor,
	) => {
		const { path, method, summary, description, parameters, responses } =
			options

		const operationId = String(propertyKey)

		const HttpMethodDecorator = HTTP_METHOD_DECORATORS[method]
		const decorators: MethodDecorator[] = [
			HttpMethodDecorator(resolvePath(path, method)),
			ApiOperation({
				description,
				operationId,
				summary,
			}),
		]

		const httpCode = getHttpStatusCode(responses)
		decorators.push(HttpCode(httpCode))

		if (parameters?.headers) {
			decorators.push(...createHeaderDecorators(parameters.headers))
		}

		if (parameters?.params) {
			decorators.push(...createParamDecorators(parameters.params))
		}

		if (parameters?.query) {
			decorators.push(...createQueryDecorators(parameters.query))
		}

		if (parameters?.body) {
			decorators.push(createBodyDecorator(parameters.body))
		}

		if (responses) {
			decorators.push(...createResponseDecorators(responses))
		}

		decorators.push(...createDefaultQueryDecorators())
		decorators.push(...createDefaultErrorResponses())

		const version = options.version ?? 1

		decorators.push(Version(version.toString().replace('v', '')))

		return applyDecorators(...decorators)(target, propertyKey, descriptor)
	}
}
